---

project_name: hub
before:
  hooks:
    - go mod tidy
builds:
  - env: [CGO_ENABLED=0]
    binary: hub
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    id: "cli"
    dir: .
    main: ./main.go
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Commit={{.Commit}} -X main.Date={{.Date}}

archives:
  - id: cli-archive
    format: tar.gz
    files:
      - none*
    builds:
      - cli
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "zcubbs/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "zcubbs/{{ .ProjectName }}:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "zcubbs/{{ .ProjectName }}:{{ .Version }}-arm64"
      - "zcubbs/{{ .ProjectName }}:latest-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
  - name_template: zcubbs/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - zcubbs/{{ .ProjectName }}:{{ .Version }}-amd64
      - zcubbs/{{ .ProjectName }}:{{ .Version }}-arm64
  - name_template: zcubbs/{{ .ProjectName }}:latest
    image_templates:
      - zcubbs/{{ .ProjectName }}:latest-amd64
      - zcubbs/{{ .ProjectName }}:latest-arm64
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^conf:'
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
signs:
  - cmd: gpg
    args:
      - --output
      - $signature
      - --detach-sig
      - $artifact
    signature: ${artifact}.sig
    artifacts: none
release:
  github:
    owner: zcubbs
    name: hub
  draft: false
  prerelease: auto
  header: |
    ## ({{ .Date }})

    Welcome to this new release!
  footer: |
    ## Thanks!
    Those were the changes on {{ .Tag }}!
  name_template: "{{.Tag}}"
