---
groups:
  - caption: "Group 1"
    links:
      - caption: Test/tag 1
        url: "https://google.com"

      - caption: Test Link
        url: "https://google.com"

      - caption: Test Link
        url: "https://google.com"

