---
links:
  - caption: Docs
    url: "https://google.com"
    icon: "ph-book-bookmark"
  - caption: Blog
    url: "https://google.com"
    icon: "ph-coffee"
  - caption: Pulse
    url: "https://google.com"
    icon: "ph-heartbeat"
groups:
  - caption: "Group 1"
    id: "group-1"
    links:
      - caption: Group 2
        url: "group-2"
        newTab: false
        external: false

      - caption: Test Link
        url: "https://google.com"
        external: true
        newTab: true

      - caption: Test Link
        url: "https://google.com"
        newTab: false
        external: true

      - caption: Test Link
        url: "https://google.com"
        newTab: false
        external: true

      - caption: Test Link
        url: "https://google.com"
        newTab: false
        external: true
  - caption: "Group 2"
    hidden: true
    id: "group-2"
    links:
      - caption: Test/tag 1
        url: "https://google.com"
        newTab: true
        external: true

      - caption: Test Link
        url: "https://google.com"
        newTab: true
        external: true

      - caption: Test Link
        url: "https://google.com"
        newTab: true
        external: true
  - caption: "Group 3"
    hidden: false
    id: "group-3"
    links:
      - caption: Test/tag 1
        url: "https://google.com"
        newTab: false
        external: false

      - caption: Test Link
        url: "https://google.com"
        newTab: false
        external: false

      - caption: Test Link
        url: "https://google.com"
        newTab: false
        external: false

      - caption: Test Link
        url: "https://google.com"
        newTab: false
        external: false

      - caption: Test Link
        url: "https://google.com"
        newTab: false
        external: false

